mv air_strike.vtf                 1104.vtf
mv ambassador.vtf                 61.vtf
mv amputator.vtf                  304.vtf
mv ap_sap.vtf                     933.vtf
mv apoco_fists.vtf                587.vtf
mv atomizer.vtf                   450.vtf
mv awper_hand.vtf                 851.vtf
mv axtinguisher.vtf               38.vtf
mv baby_face_blaster.vtf          772.vtf
mv back_scatter.vtf	              1103.vtf
mv back_scratcher.vtf             326.vtf
mv backburner.vtf                 40.vtf
REM mv base_jumper.vtf	              1101.vtf
mv bat.vtf                        0.vtf
mv bat_outta_hell.vtf	            939.vtf
mv batsaber.vtf                   30667.vtf
mv battalions_backup.vtf          226.vtf
mv bazzar_bargain.vtf             402.vtf
mv beggars_bazooka.vtf            730.vtf
mv big_earner.vtf                 461.vtf
mv big_kill.vtf                   161.vtf
mv black_box.vtf                  228.vtf
mv black_rose.vtf                 727.vtf
mv blutsauger.vtf                 36.vtf
mv bonesaw.vtf                    8.vtf
mv bonk.vtf                       46.vtf
mv booties.vtf                    405.vtf
mv bootlegger.vtf                 608.vtf
mv boston_basher.vtf              325.vtf
mv bottle.vtf                     1.vtf
mv brass_beast.vtf                312.vtf
mv bread_bite.vtf                 1100.vtf
mv buff_banner.vtf                129.vtf
mv buffalo_steak.vtf              311.vtf
mv build_pda.vtf                  25.vtf
mv bushwacka.vtf                  232.vtf
mv candy_cane.vtf                 317.vtf
mv capper.vtf                     30666.vtf
mv chargin_targe.vtf              131.vtf
mv claidheamh_mor.vtf             327.vtf
mv classic.vtf                    1098.vtf
mv cleaners_carbine.vtf           751.vtf
mv cloak_and_dagger.vtf           60.vtf
mv concherer.vtf                  354.vtf
mv connivers_kunai.vtf            356.vtf
mv conscientious_objector.vtf     474.vtf
mv cow_mangler.vtf                441.vtf
mv cozy_camper.vtf                642.vtf
mv crit_a_cola.vtf                163.vtf
mv crossing_guard.vtf             1127.vtf
mv crusaders_crossbow.vtf	305.vtf
mv dalokas_bar.vtf	159.vtf
mv darwins_danger_shield.vtf	231.vtf
mv dead_ringer.vtf	59.vtf
mv degreaser.vtf    215.vtf
mv Destruction_pda.vtf	26.vtf
mv detonator.vtf    351.vtf
mv diamondback.vtf	525.vtf
mv direct_hit.vtf	127.vtf
mv disguise_kit.vtf	27.vtf
mv displinary_action.vtf	447.vtf
mv dragons_fury.vtf               1178.vtf
mv enforcer.vtf	460.vtf
mv enthusiasts_timepiece.vtf	297.vtf
mv equilizer.vtf	128.vtf
mv escape_plan.vtf	775.vtf
mv eureka_effect.vtf	589.vtf
mv eviction_notice.vtf	426.vtf
mv eyelander.vtf	132.vtf
mv family_buisness.vtf	425.vtf
mv fan_of_war.vtf	355.vtf
mv fire_axe.vtf    2.vtf
mv fishcake.vtf	433.vtf
mv fists.vtf	5.vtf
mv fists_of_steel.vtf	331.vtf
mv flame_thrower.vtf    21.vtf
mv flare_gun.vtf    39.vtf
mv flying_guillotine.vtf  812.vtf
mv force_of_nature.vtf	45.vtf
mv fortified_compound.vtf	1092.vtf
mv freedom_staff.vtf	880.vtf
mv frontier_justice.vtf	141.vtf
mv frying_pan.vtf	264.vtf
mv gas_passer.vtf	1180.vtf
mv giger_counter.vtf	30668.vtf
mv gloves_running.vtf	239.vtf
mv grenade_launcher.vtf	19.vtf
mv gunboats.vtf	133.vtf
mv gunslinger.vtf	142.vtf
mv half_zatoichi.vtf	357.vtf
mv ham_shank.vtf	1013.vtf
mv hitmans_heatmaker.vtf	752.vtf
mv holiday_punch.vtf	656.vtf
mv holy_mackerel.vtf	221.vtf
mv homewrecker.vtf    153.vtf
mv horseless_headless_horsemanns_headtaker.vtf    266.vtf
mv hot_hand.vtf	1181.vtf
mv huntsman.vtf	56.vtf
mv huo_long_heater.vtf	811.vtf
mv invis_watch.vtf	30.vtf
mv iron_bomber.vtf	1151.vtf
mv iron_curtian.vtf	298.vtf
mv jag.vtf	329.vtf
mv jarate.vtf	58.vtf
mv killing_gloves_of_boxing.vtf	43.vtf
mv knife.vtf	4.vtf
mv kritzkrieg.vtf	35.vtf
mv kukri.vtf	3.vtf
mv letranger.vtf	224.vtf
mv liberty_launcher.vtf	414.vtf
mv loch_n_load.vtf 308.vtf
mv lolichop.vtf	739.vtf
mv loose_cannon.vtf	996.vtf
mv lugermorph.vtf	160.vtf
mv machina.vtf	526.vtf
mv mad_milk.vtf	222.vtf
mv manmelter.vtf    595.vtf
mv mantreads.vtf	444.vtf
mv market_gardener.vtf	416.vtf
mv maul.vtf    466.vtf
mv maul.vtf	466.vtf
mv medi_gun.vtf	29.vtf
mv memory_maker.vtf	954.vtf
mv minigun.vtf	15.vtf
mv mutated_milk.vtf	1121.vtf
mv natasha.vtf	41.vtf
mv necro_smasher.vtf	1123.vtf
mv neon_annihilator.vtf    813.vtf
mv nessie_nine_iron.vtf	482.vtf
mv nostromo_napalmer.vtf    30474.vtf
mv original.vtf	513.vtf
mv overdose.vtf	412.vtf
mv pain_train.vtf	154.vtf
mv panic_attack.vtf	1153.vtf
mv persian_persuader.vtf	404.vtf
mv phlogistinator.vtf    594.vtf
mv pistol.vtf	22.vtf
mv pompson.vtf	588.vtf
mv postal_pummeler.vtf    457.vtf
mv powerjack.vtf    214.vtf
mv pretty_boys_pocket_pistol.vtf	773.vtf
mv prinny_machete.vtf	30758.vtf
mv quackenbirdt.vtf	947.vtf
mv quick_fix.vtf	411.vtf
mv quickiebomb_launcher.vtf	1150.vtf
mv rainblower.vtf	741.vtf
mv razerback.vtf	57.vtf
mv red_tape_recorder.vtf	810.vtf
mv rescue_ranger.vtf	997.vtf
mv reserve_shooter.vtf	415.vtf
mv revolver.vtf	24.vtf
mv righteous_bison.vtf	442.vtf
mv robo_sandvich.vtf	863.vtf
mv rocket_jumper.vtf	237.vtf
mv rocket_launcher.vtf	18.vtf
mv sandman.vtf	44.vtf
mv sandvich.vtf	42.vtf
mv sapper.vtf	735.vtf
mv saxxy.vtf	423.vtf
mv scattergun.vtf	13.vtf
mv scorch_shot.vtf    740.vtf
mv scotsmans_skullcutter.vtf	172.vtf
mv scottish_handshake.vtf	609.vtf
mv scottish_resistance.vtf	130.vtf
mv second_banana.vtf	1190.vtf
mv self_aware_beauty_mark.vtf	1105.vtf
mv shahanshah.vtf	401.vtf
mv sharp_dresser.vtf	638.vtf
mv sharpen_volcano_fragment.vtf    348.vtf
mv shooting_star.vtf	30665.vtf
mv short_circuit.vtf	528.vtf
mv shortstop.vtf	220.vtf
mv shotguns.vtf	9.vtf
mv shovel.vtf	6.vtf
mv smg.vtf	16.vtf
mv snack_attack.vtf	1102.vtf
mv sniper_rifle.vtf	14.vtf
mv soda_popper.vtf	448.vtf
mv solumn_vow.vtf	413.vtf
mv southern_hospitality.vtf	155.vtf
mv splendid_screen.vtf	406.vtf
mv splendid_screen.vtf	406.vtf
mv spy_cicle.vtf	649.vtf
mv sticky_jumper.vtf	265.vtf
mv stickybomb_launcher.vtf	20.vtf
mv sun_on_a_stick.vtf	349.vtf
mv sydney_sleeper.vtf	230.vtf
mv syringe_gun.vtf	17.vtf
mv thermal_thruster.vtf           1179.vtf
mv third_degree.vtf    593.vtf
mv third_degree.vtf	593.vtf
mv three_rune_blade.vtf	452.vtf
mv tide_turner.vtf	1099.vtf
mv tide_turner.vtf	1099.vtf
mv tomislav.vtf	424.vtf
mv tomislav.vtf	424.vtf
mv tribalmans_shiv.vtf	171.vtf
mv ubersaw.vtf	37.vtf
mv ullapool_caber.vtf	307.vtf
mv ullapool_caber.vtf	307.vtf
mv unarmed_combat.vtf	572.vtf
mv vaccinator.vtf	998.vtf
mv vaccinator.vtf	998.vtf
mv vita_saw.vtf	173.vtf
mv wanga_prick.vtf  574.vtf
mv warriors_spirit.vtf	310.vtf
mv widowmaker.vtf	527.vtf
mv winger.vtf 449.vtf
mv wrangler.vtf	140.vtf
mv wrap_assassin.vtf	648.vtf
mv wrench.vtf	7.vtf
mv your_eternal_reward.vtf	225.vtf
