rename air_strike.vtf   1104.vtf
rename amputator.vtf    304.vtf
rename apoco_fists.vtf  587.vtf
rename bat_outta_hell.vtf	939.vtf
rename base_jumper.vtf	1101.vtf
rename blutsauger.vtf	36.vtf
rename bonesaw.vtf	8.vtf
rename booties.vtf	405.vtf
rename bootlegger.vtf	608.vtf
rename bottle.vtf	1.vtf
rename brass_beast.vtf	312.vtf
rename bread_bite.vtf	1100.vtf
rename buffalo_steak.vtf	311.vtf
rename build_pda.vtf	25.vtf
rename capper.vtf	30666.vtf
rename chargin_targe.vtf	131.vtf
rename claidheamh_mor.vtf	327.vtf
rename conscientious_objector.vtf	474.vtf
rename crossing_guard.vtf	1127.vtf
rename crusaders_crossbow.vtf	305.vtf
rename dalokas_bar.vtf	159.vtf
rename degreaser.vtf	215.vtf
rename Destruction_pda.vtf	26.vtf
rename eureka_effect.vtf	589.vtf
rename eviction_notice.vtf	426.vtf
rename eyelander.vtf	132.vtf
rename family_buisness.vtf	425.vtf
rename fishcake.vtf	433.vtf
rename fists.vtf	5.vtf
rename fists_of_steel.vtf	331.vtf
rename freedom_staff.vtf	880.vtf
rename frontier_justice.vtf	141.vtf
rename frying_pan.vtf	264.vtf
rename giger_counter.vtf	30668.vtf
rename gloves_running.vtf	239.vtf
rename gunslinger.vtf	2049.vtf
rename half_zatoichi.vtf	357.vtf
rename ham_shank.vtf	1013.vtf
rename holiday_punch.vtf	656.vtf
rename horseless_headless_horsemanns_headtaker.vtf	266.vtf
rename huo_long_heater.vtf	811.vtf
rename iron_bomber.vtf	1151.vtf
rename iron_curtian.vtf	298.vtf
rename jag.vtf	329.vtf
rename loch_n_load.vtf 308.vtf
rename loose_cannon.vtf	996.vtf
rename lugermorph.vtf	160.vtf
rename necro_smasher.vtf	1123.vtf
rename nessie_nine_iron.vtf	482.vtf
rename pain_train.vtf	154.vtf
rename panic_attack.vtf	1153.vtf
rename persian_persuader.vtf	404.vtf
rename pompson.vtf	588.vtf
rename prinny_machete.vtf	30758.vtf
rename quickiebomb_launcher.vtf	1150.vtf
rename quick_fix.vtf	411.vtf
rename rescue_ranger.vtf	997.vtf
rename reserve_shooter.vtf	415.vtf
rename robo_sandvich.vtf	863.vtf
rename saxxy.vtf	423.vtf
rename scotsmans_skullcutter.vtf	172.vtf
rename scottish_handshake.vtf	609.vtf
rename scottish_resistance.vtf	130.vtf
rename second_banana.vtf	1190.vtf
rename short_circuit.vtf	528.vtf
rename solumn_vow.vtf	413.vtf
rename splendid_screen.vtf	406.vtf
rename tide_turner.vtf	1099.vtf
rename tomislav.vtf	424.vtf
rename ullapool_caber.vtf	307.vtf
rename vaccinator.vtf	998.vtf
rename warriors_spirit.vtf	310.vtf
rename widowmaker.vtf	527.vtf
rename axtinguisher.vtf    38.vtf
rename back_scratcher.vtf    326.vtf
rename fire_axe.vtf    2.vtf
rename homewrecker.vtf    153.vtf
rename maul.vtf    466.vtf
rename neon_annihilator.vtf    813.vtf
rename postal_pummeler.vtf    457.vtf
rename powerjack.vtf    214.vtf
rename sharpen_volcano_fragment.vtf    348.vtf
rename third_degree.vtf    593.vtf
rename backburner.vtf    40.vtf
rename degreaser.vtf    215.vtf
rename flame_thrower.vtf    21.vtf
rename nostromo_napalmer.vtf    30474.vtf
rename phlogistinator.vtf    594.vtf
rename detonator.vtf    351.vtf
rename flare_gun.vtf    39.vtf
rename manmelter.vtf    595.vtf
rename scorch_shot.vtf    740.vtf
rename thermal_thruster.vtf    1179.vtf
rename atomizer.vtf    450.vtf
rename bat.vtf    0.vtf
rename batsaber.vtf    30667.vtf
rename boston_basher.vtf    325.vtf
rename ambassador.vtf	61.vtf
rename ap_sap.vtf	933.vtf
rename awper_hand.vtf	851.vtf
rename baby_face_blaster.vtf	772.vtf
rename back_scatter.vtf	1103.vtf
rename bazzar_bargain.vtf	402.vtf
rename beggars_bazooka.vtf	730.vtf
rename big_earner.vtf	461.vtf
rename big_kill.vtf	161.vtf
rename black_box.vtf	228.vtf
rename black_rose.vtf	727.vtf
rename buff_banner.vtf	129.vtf
rename bushwacka.vtf	232.vtf
rename candy_cane.vtf	317.vtf
rename classic.vtf	1098.vtf
rename cleaners_carbine.vtf	751.vtf
rename cloak_and_dagger.vtf	60.vtf
rename concherer.vtf	354.vtf
rename connivers_kunai.vtf	356.vtf
rename cow_mangler.vtf	441.vtf
rename cozy_camper.vtf	642.vtf
rename crossing_guard.vtf	1127.vtf
rename darwins_danger_shield.vtf	231.vtf
rename dead_ringer.vtf	59.vtf
rename diamondback.vtf	525.vtf
rename direct_hit.vtf	127.vtf
rename disguise_kit.vtf	27.vtf
rename displinary_action.vtf	447.vtf
rename enforcer.vtf	460.vtf
rename enthusiasts_timepiece.vtf	297.vtf
rename equilizer.vtf	128.vtf
rename escape_plan.vtf	775.vtf
rename fan_of_war.vtf	355.vtf
rename fire_axe.vtf	2.vtf
rename force_of_nature.vtf	45.vtf
rename fortified_compound.vtf	1092.vtf
rename grenade_launcher.vtf	19.vtf
rename gunboats.vtf	133.vtf
rename hitmans_heatmaker.vtf	752.vtf
rename holy_mackerel.vtf	221.vtf
rename huntsman.vtf	56.vtf
rename invis_watch.vtf	30.vtf
rename jarate.vtf	58.vtf
rename killing_gloves_of_boxing.vtf	43.vtf
rename knife.vtf	4.vtf
rename kritzkrieg.vtf	35.vtf
rename kukri.vtf	3.vtf
rename letranger.vtf	224.vtf
rename liberty_launcher.vtf	414.vtf
rename machina.vtf	526.vtf
rename mad_milk.vtf	222.vtf
rename mantreads.vtf	444.vtf
rename market_gardener.vtf	416.vtf
rename maul.vtf	466.vtf
rename medi_gun.vtf	29.vtf
rename minigun.vtf	15.vtf
rename natasha.vtf	41.vtf
rename original.vtf	513.vtf
rename overdose.vtf	412.vtf
rename pistol.vtf	22.vtf
rename pretty_boys_pocket_pistol.vtf	773.vtf
rename quackenbirdt.vtf	947.vtf
rename razerback.vtf	57.vtf
rename red_tape_recorder.vtf	810.vtf
rename revolver.vtf	24.vtf
rename righteous_bison.vtf	442.vtf
rename rocket_jumper.vtf	237.vtf
rename rocket_launcher.vtf	18.vtf
rename sandman.vtf	44.vtf
rename sandvich.vtf	42.vtf
rename sapper.vtf	735.vtf
rename scattergun.vtf	13.vtf
rename self_aware_beauty_mark.vtf	1105.vtf
rename shahanshah.vtf	401.vtf
rename sharp_dresser.vtf	638.vtf
rename shooting_star.vtf	30665.vtf
rename shortstop.vtf	220.vtf
rename shotguns.vtf	9.vtf
rename shovel.vtf	6.vtf
rename smg.vtf	16.vtf
rename snack_attack.vtf	1102.vtf
rename sniper_rifle.vtf	14.vtf
rename soda_popper.vtf	448.vtf
rename southern_hospitality.vtf	155.vtf
rename splendid_screen.vtf	406.vtf
rename spy_cicle.vtf	649.vtf
rename stickybomb_launcher.vtf	20.vtf
rename sticky_jumper.vtf	265.vtf
rename sun_on_a_stick.vtf	349.vtf
rename sydney_sleeper.vtf	230.vtf
rename syringe_gun.vtf	17.vtf
rename thermal_thruster.vtf	1179.vtf
rename third_degree.vtf	593.vtf
rename three_rune_blade.vtf	452.vtf
rename tide_turner.vtf	1099.vtf
rename tomislav.vtf	424.vtf
rename tribalmans_shiv.vtf	171.vtf
rename ubersaw.vtf	37.vtf
rename ullapool_caber.vtf	307.vtf
rename unarmed_combat.vtf	572.vtf
rename vaccinator.vtf	998.vtf
rename vita_saw.vtf	173.vtf
rename wrap_assassin.vtf	648.vtf
rename wrench.vtf	7.vtf
rename your_eternal_reward.vtf	225.vtf
rename wrangler.vtf	140.vtf
rename memory_maker.vtf	954.vtf
rename dragon_fury.vtf	1178.vtf
rename rainblower.vtf	741.vtf
rename gas_passer.vtf	1180.vtf
rename hot_hand.vtf	1181.vtf
rename lolichop.vtf	739.vtf
rename bonk_cola.vtf	46.vtf
rename crit_cola.vtf	163.vtf
rename mutated_milk.vtf	1121.vtf
rename battalions_backup.vtf	226.vtf
rename wanga_prick.vtf  574.vtf
rename winger.vtf 449.vtf